### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [abuuzayr/coronavirus-apps#6]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

http://open-source-covid-19.weileizeng.com/

Cheers!

**Comment by WeileiZeng** [comment]
I have changed the layout of the page, as well as the domain. I would appreciate you updating it in README. Thanks!

Meanwhile, you might want to check out this list
https://github.com/soroushchehresa/awesome-coronavirus

**Comment by abuuzayr** [comment]
thank you for finding this list @WeileiZeng ! I am honored because I saw your list first and it inspired me. 

Thank you for reminding me about the awesome-coronavirus list as well, I should add it in too.. 

Thank you for your hard work daily in helping everyone get through this difficult time better!

**Comment by WeileiZeng** [comment]
Thank you for your encouragement!
